# Generated by Django 3.0.8 on 2023-02-19 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('mobile_no', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('national_id', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='make',
            fields=[
                ('make_id', models.AutoField(primary_key=True, serialize=False)),
                ('make_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='model',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=200)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.make')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='years',
            fields=[
                ('year_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Project')),
            ],
        ),
        migrations.CreateModel(
            name='sellpart',
            fields=[
                ('sell_id', models.AutoField(primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
                ('discount', models.CharField(max_length=200)),
                ('discounted_amount', models.CharField(max_length=200)),
                ('sell_price', models.CharField(max_length=200)),
                ('sell_price_after_discount', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('sub_total', models.CharField(max_length=200)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.admins')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.make')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.model')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.years')),
            ],
        ),
        migrations.CreateModel(
            name='addpart',
            fields=[
                ('part_id', models.AutoField(primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=200)),
                ('part_no', models.IntegerField()),
                ('is_scrap', models.BooleanField(default=False)),
                ('sell_price', models.CharField(max_length=200)),
                ('part_location', models.CharField(max_length=200)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.admins')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.make')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.model')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.years')),
            ],
        ),
        migrations.CreateModel(
            name='addcar',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_price', models.IntegerField()),
                ('purchase_date', models.DateTimeField(auto_now=True)),
                ('year', models.CharField(max_length=200)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.admins')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.make')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.model')),
            ],
        ),
    ]
